### ISSUE TITLE
Fails to start (Debian 11, Gnome)

### ISSUE THREAD

**Issue by bound-variable** [andrewsomething/typecatcher#19]
Terminal output:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/typecatcher_lib/Application.py", line 30, in on_activate
    self.window = TypeCatcherWindow.TypeCatcherWindow()
  File "/usr/lib/python3/dist-packages/typecatcher_lib/Window.py", line 47, in __new__
    builder = get_builder('TypeCatcherWindow')
  File "/usr/lib/python3/dist-packages/typecatcher_lib/helpers.py", line 44, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/typecatcher_lib/Builder.py", line 86, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

- OS: Debian 11
- DE: Gnome 3.38.6
- App version: 0.3 (from Debian's main repo)

**Comment by istiak101** [comment]
You have these options.

1) Wait for maintainer to package 0.4 which have the fix
2) Download and compile the release yourself
3) Manually editing Builder.py

https://github.com/andrewsomething/typecatcher/issues/16
https://github.com/jamiemcg/Remarkable/issues/382

**Comment by akwala** [comment]
> [jamiemcg/Remarkable#382](https://github.com/jamiemcg/Remarkable/issues/382)

This worked in Kubuntu 22.04, with Python 3.10.4:

```diff
diff --git a/typecatcher_lib/Builder.py b/typecatcher_lib/Builder.py
index 359ffc6..c93b68f 100644
--- a/typecatcher_lib/Builder.py
+++ b/typecatcher_lib/Builder.py
@@ -84,7 +84,8 @@ class Builder(Gtk.Builder):
         tree = ElementTree()
         tree.parse(filename)
 
-        ele_widgets = self.get_iterator(tree, "object")
+        # ele_widgets = self.get_iterator(tree, "object")
+        ele_widgets = tree.iter("object")
         for ele_widget in ele_widgets:
             name = ele_widget.attrib['id']
             widget = self.get_object(name)
```

**Comment by hellobritt** [comment]
I also had to change line 109 in Builder.py on Ubuntu 22.10 

```
        # ele_signals = tree.getiterator("signal") [my change]
        ele_signals = tree.iter("signal")
        for ele_signal in ele_signals:
            self.glade_handler_dict.update(
            {ele_signal.attrib["handler"]: None})
```

**Comment by hortiz97** [comment]
On /usr/lib/python3/dist-packages/typecatcher_lib/Builder.py

Changed line 86 for

```
ele_widgets = tree.iter("object")
        for ele_widget in ele_widgets:
            name = ele_widget.attrib['id']
            widget = self.get_object(name)
```

as @akwala suggested

And line 109 for

```
ele_signals = tree.iter("signal")
        for ele_signal in ele_signals:
            self.glade_handler_dict.update(
            {ele_signal.attrib["handler"]: None})
```

as @hellobritt suggested

It works again, thanks

Tested on KDE Neon 22.04 Jammy

**Comment by jstomw** [comment]
The same issue on Kubuntu

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/typecatcher_lib/Application.py", line 30, in on_activate
    self.window = TypeCatcherWindow.TypeCatcherWindow()
  File "/usr/lib/python3/dist-packages/typecatcher_lib/Window.py", line 47, in __new__
    builder = get_builder('TypeCatcherWindow')
  File "/usr/lib/python3/dist-packages/typecatcher_lib/helpers.py", line 44, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/typecatcher_lib/Builder.py", line 86, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'

Linux yoga 5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 14:02:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

**Comment by ghost** [comment]
Same issue, Debian 12

**Comment by evdcush** [comment]
# Your error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/typecatcher_lib/Application.py", line 30, in on_activate
    self.window = TypeCatcherWindow.TypeCatcherWindow()
  File "/usr/lib/python3/dist-packages/typecatcher_lib/Window.py", line 47, in __new__
    builder = get_builder('TypeCatcherWindow')
  File "/usr/lib/python3/dist-packages/typecatcher_lib/helpers.py", line 44, in get_builder
    builder.add_from_file(ui_filename)
  File "/usr/lib/python3/dist-packages/typecatcher_lib/Builder.py", line 86, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

# The fix:

Backup the file.
```sh
cp /usr/lib/python3/dist-packages/typecatcher_lib/Builder.py ~/Builder.bkp.py

```

Replace the problem lines.
```sh
sudo sed -i 's/tree.getiterator/tree.iter/g' /usr/lib/python3/dist-packages/typecatcher_lib/Builder.py
```

**Comment by rolodoom** [comment]
I used the fixed proposed by by @evdcush, replacing `tree.getiterator` by `tree.iter` on `Builder.py`. Tested on Debian 12 with KDE and it typecatcher started working. Thanks.
